pimp: shorten var

diff --git a/pimp b/pimp
--- a/pimp
+++ b/pimp
@@ -2,10 +2,10 @@
 
 DPATH_MUSIC="${DPATH_MUSIC-"$HOME/Music"}"
 DPATH_PIMP_MPV_CFG="$(dirname "$(realpath "$0")")/etc/mpv"
-FPATH_PIMP_PLAYLIST="${FPATH_PIMP_PLAYLIST-"$HOME/.cache/pimp.playlist"}"
+FPATH_PLAYLIST="${FPATH_PLAYLIST-"$HOME/.cache/pimp.playlist"}"
 
 export DPATH_MUSIC
-export FPATH_PIMP_PLAYLIST
+export FPATH_PLAYLIST
 
 check_prerequisites()
 {
@@ -40,7 +40,7 @@ create_list()
 	then
 		dpath_full="$(realpath "$DPATH_MUSIC/$*")"
 
-		find -L "$dpath_full" -type f | sort > "$FPATH_PIMP_PLAYLIST"
+		find -L "$dpath_full" -type f | sort > "$FPATH_PLAYLIST"
 	fi
 }
 
@@ -57,7 +57,7 @@ item_play()
 		break
 	done
 
-	if [ -f "$FPATH_PIMP_PLAYLIST" ]
+	if [ -f "$FPATH_PLAYLIST" ]
 	then
 		clear
 		printf 'PiMP: initiating the slap... (⌐■_■)\n\n'
@@ -80,10 +80,10 @@ item_play()
 			--loop-file=no \
 			--display-tags= \
 			--audio-pitch-correction=no --af-add=scaletempo=speed=both \
-			--playlist="$FPATH_PIMP_PLAYLIST" "$mpv_arg_cfgdir" \
+			--playlist="$FPATH_PLAYLIST" "$mpv_arg_cfgdir" \
 			"$@"
 	else
-		printf 'pimp: cannot find %s\n' "$FPATH_PIMP_PLAYLIST" >&2
+		printf 'pimp: cannot find %s\n' "$FPATH_PLAYLIST" >&2
 		return 1
 	fi
 }
@@ -141,7 +141,7 @@ list_dirs()
 
 list_filter()
 {
-	modtime_pimp_list_pre="$(stat --format '%Y' "$FPATH_PIMP_PLAYLIST")"
+	modtime_pimp_list_pre="$(stat --format '%Y' "$FPATH_PLAYLIST")"
 
 	item_sound select
 
@@ -159,7 +159,7 @@ list_filter()
 		--no-mouse \
 		--header-lines=0 \
 		--layout=reverse \
-		--bind 'enter:select-all+accept+execute(rm -f "$FPATH_PIMP_PLAYLIST")' \
+		--bind 'enter:select-all+accept+execute(rm -f "$FPATH_PLAYLIST")' \
 		--bind 'change:first' \
 		--bind 'backward-eof:execute-silent(printf clear | espeak -a 250 -s 300)' \
 		--bind 'home:first' \
@@ -170,11 +170,11 @@ list_filter()
 		--bind 'tab:abort' | \
 	while read -r f
 	do
-		printf '%s/%s\n' "$DPATH_MUSIC" "$f" >> "$FPATH_PIMP_PLAYLIST"
+		printf '%s/%s\n' "$DPATH_MUSIC" "$f" >> "$FPATH_PLAYLIST"
 		continue
 	done
 
-	modtime_pimp_list_post="$(stat --format '%Y' "$FPATH_PIMP_PLAYLIST")"
+	modtime_pimp_list_post="$(stat --format '%Y' "$FPATH_PLAYLIST")"
 
 	if [ "$modtime_pimp_list_post" != "$modtime_pimp_list_pre" ]
 	then
@@ -182,7 +182,7 @@ list_filter()
 	fi
 }
 
-mkdir "$(dirname "$FPATH_PIMP_PLAYLIST")" > /dev/null 2>&1
+mkdir "$(dirname "$FPATH_PLAYLIST")" > /dev/null 2>&1
 
 if ! check_prerequisites
 then
@@ -211,7 +211,7 @@ case "$1" in
 		;;
 	
 	*)
-		if [ -f "$FPATH_PIMP_PLAYLIST" ]
+		if [ -f "$FPATH_PLAYLIST" ]
 		then
 			item_play
 		fi
