pimp: change prereq system to include suggestions
- create two prerequisite lists to account for programs that 1) must
  exist on a system and 2) should exist on a system to take full
  advantage of pimp, but are optional.
- mark `fzf`, `mpv` and pimp itself as necessary programs in $PATH.
- mark `espeak` and `sox` as optional programs in $PATH.

diff --git a/pimp b/pimp
--- a/pimp
+++ b/pimp
@@ -33,7 +33,8 @@
 #  SOFTWARE.
 
 arg="$(printf '%s\n' "$*" | awk '{$1=""; print}' | sed 's/^[[:space:]]*//g')"
-prereq="pimp espeak sox fzf mpv"
+prereq_stop="pimp fzf mpv"
+prereq_cont="espeak sox"
 
 PIMP_DPATH_CACHE="${PIMP_DPATH_CACHE-"${HOME}/.cache/pimp"}"
 PIMP_DPATH_CONF="${PIMP_DPATH_CONF-"${HOME}/.config/pimp"}"
@@ -244,8 +245,8 @@ play_music()
 		fi
 	}
 
-	pkill espeak
-	pkill play
+	pkill -x espeak
+	pkill -x play
 
 	local opt="$(printf '%s' "$*" | awk '{print $1}' | grep -o '^\-[a-zA-Z0-9]*')"
 	local str="$(printf '%s' "$*" | sed 's/^\-[a-zA-Z0-9]*//g' | sed 's/^[[:space:]]*//g')"
@@ -361,7 +362,7 @@ check_prerequisites()
 			then
 				if [ ${err} -eq 0 ]
 				then
-					printf 'pimp: list of prerequisite programs not found within $PATH:\n\n' >&2
+					printf 'pimp: prerequisite programs not found in $PATH:\n' >&2
 					err=1
 				fi
 				
@@ -443,6 +444,11 @@ play_sound()
 {
 	#  produces sound effects for auditory navigation.
 
+	if ! command -v sox > /dev/null 2>&1
+	then
+		return 1
+	fi
+
 	case "$1" in
 		select)
 			play -qn synth sine 2000 trim 0 0.05 gain -30
@@ -470,6 +476,11 @@ play_tts()
 
 	local str="$*"
 	local sys="$(uname -s | tr '[:upper:]' '[:lower:]')"
+
+	if ! command -v espeak > /dev/null 2>&1
+	then
+		return 1
+	fi
 
 	case "${sys}" in
 		linux)
@@ -630,9 +641,14 @@ set_term_title()
 	printf "\033]0;pimp\007"  
 }
 
-if ! check_prerequisites "${prereq}"
+if ! check_prerequisites "${prereq_stop}"
 then
 	exit 2
+fi
+
+if ! check_prerequisites "${prereq_cont}"
+then
+	printf '\npimp: continuing...\n' >&2
 fi
 
 if ! create_program_dirs
